'''
Create a program that will play the “cows and bulls” game with the user. The game works like this:

Randomly generate a 4-digit number. Ask the user to guess a 4-digit number(Digits should not be repeated). For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout teh game and tell the user at the end.

Say the number generated by the computer is 1038. An example interaction could look like this:

  Welcome to the Cows and Bulls Game! 
  Enter a number: 
  >>> 1234
  2 cows, 0 bulls
  >>> 1250
  1 cow, 1 bull
  ...
Until the user guesses the number.
'''

import random

def generate_secret_number():
  """Generates a random 4-digit number with no repeated digits."""
  secret_number = ""
  while len(secret_number) < 4:
    digit = random.randint(0, 9)
    if digit not in secret_number:
      secret_number += str(digit)
  return secret_number

def calculate_cows_and_bulls(secret_number, guess):
  """Calculates the number of cows and bulls in a guess."""
  cows = 0
  bulls = 0
  for i in range(4):
    if secret_number[i] == guess[i]:
      cows += 1
    elif secret_number[i] in guess:
      bulls += 1
  return cows, bulls

def play_cows_and_bulls():
  """Plays the Cows and Bulls game with the user."""

  secret_number = generate_secret_number()
  num_guesses = 0

  print("Welcome to the Cows and Bulls Game!")

  while True:
    guess = input("Enter a number: ")

    if len(guess) != 4 or any(digit in guess for digit in range(10) if guess.count(digit) > 1):
      print("Invalid guess. Please enter a 4-digit number with no repeated digits.")
      continue

    cows, bulls = calculate_cows_and_bulls(secret_number, guess)

    print(f"{cows} cows, {bulls} bulls")

    if cows == 4:
      break

    num_guesses += 1

  print(f"Congratulations! You guessed the correct number in {num_guesses} guesses.")

if __name__ == "__main__":
  play_cows_and_bulls()